# Generated by Django 3.1.5 on 2021-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='Geodetic',
            field=models.CharField(choices=[('fs', '2~3매'), ('sc', '1~2매'), ('no', '무')], max_length=40),
        ),
        migrations.AlterField(
            model_name='manage',
            name='RFruit',
            field=models.CharField(choices=[('False', '무'), ('True', '유')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manage',
            name='RHead',
            field=models.CharField(choices=[('False', '무'), ('True', '유')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manage',
            name='RLeaf',
            field=models.CharField(choices=[('False', '무'), ('True', '유')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manage',
            name='WType',
            field=models.CharField(choices=[('ds', '다량소회'), ('sd', '소량다회')], max_length=30),
        ),
    ]
