# Generated by Django 3.1.5 on 2021-01-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210119_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='RFruit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='manage',
            name='RHead',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='manage',
            name='RLeaf',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='manage',
            name='WType',
            field=models.CharField(choices=[('ds', '다량소회'), ('sd', '소량다회')], max_length=10),
        ),
    ]
